[project]
name = "an-analysis-on-food-intake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ruinivist", email = "ruinivist@proton.me" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.10.6",
    "numpy>=2.5.2",
    "pandas>=2.3.2",
]
